version: '3'
services:
  db:
    image: postgres
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"


  quarkus-app:
    build:
      context: ../../..
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: quarkus-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/mydatabase
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
